project:
  type: book
  output-dir: docs

execute:
  execute: false

book:
  title: "金融数据获取、管理与初步分析"
  author: "邓佳鸣 (25210124)"
  date: today
  repo-url: https://github.com/JM-25MDE/dshw-p01
  chapters:
    - index.qmd
    - 01_download.ipynb
    - 02_clean.ipynb
    - 03_analysis.ipynb

resources:
  - output/

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
