project:
  type: site
  output-dir: docs

execute:
  execute: false

site:
  title: "金融数据获取、管理与初步分析"
  author: "邓佳鸣 (25210124)"

resources:
  - output/

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
